# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - run: |
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds                    
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          aws sts get-caller-identity
