# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      # pull-requests: write
      # MEMO: actions/github-script とかでPRに github.issues.createComment する場合はpull-requests: writeが必要
    env:
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
      AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
      AWS_DEFAULT_REGION: us-east-1
      
    steps:
      - run: sleep 5
      - name: Configure AWS
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - run: aws sts get-caller-identity
